- .env
- requirements.txt
- webapp/app.py
- Added a call to a GraphQL endpoint provided by directory-api to fetch employees by a provided string. It returns a list of employees if a provided string corresponds to either the first name or the last name of an employee. The comparison is strict, meaning a provided string should strictly correspond to one of first name or last name.
- Added an endpoint that receives a username string and returns a list of matched employees as an array of objects. This endpoint essentially calls a GraphQL endpoint and returns the result.
- Clone the repo
- Run `dotrun`
- Open the browser and navigate to `0.0.0.0:8104/get-users/<username>`
- Check that the result is expected
- Fixes https://warthogs.atlassian.net/browse/WD-13297
It could be helpful to provide some screenshots to aid in QAing the …
> [WD-13297] add get-users route that fetches users from directory-api

- webapp/app.py
- webapp/helper.py
- Created the `/set-reviewers` endpoint
- Takes in an array of `user_structs` and a single `webpage_id` 
- Creates a new "user" item for the user table if a user from the user_structs do not exist
- Removes all rows where “webpage_id” equals to the provided webpage ID
- Adds new rows to "Reviewer" table for the specified users
- Added a helper function to get user ID, subsequently creates a new user if the current user does not exist in the database
Example data payload with an array of user_structs and a webpage_id
```
{
"user_structs": [
{
"department": "Support Engineering",
"email": "ryan.stewart@canonical.com",
"id": "4909",
"jobTitle": "Support Engineer I",
"name": "Ryan Stewart",
"team": "Cloud Support"
},
{
"department": "Web Engineering",
"email": "britney.wang@canonical.com", …
```
> Add set reviewers endpoint

- webapp/site_repository.py
- Expanded the user object returned initially as `user_id` in the `reviewers` object in the tree.
- Run the project and create reviewers for the webpage
- Open `/get-tree/ubuntu.com`
- Check that returned json for `owner` matches `reviewers`, except for the additional `webpage_id` field
> Return reviewer as user object

- static/client/App.scss
- static/client/components/OwnerAndReviewers/CustomSearchAndFilter.tsx
- static/client/components/OwnerAndReviewers/Owner.tsx
- static/client/components/OwnerAndReviewers/OwnerAndReviewers.hooks.ts
- static/client/components/OwnerAndReviewers/OwnerAndReviewers.tsx
- static/client/components/OwnerAndReviewers/OwnerAndReviewers.types.ts
- static/client/components/OwnerAndReviewers/Reviewers.tsx
- static/client/components/OwnerAndReviewers/index.ts
- static/client/components/Search/Search.tsx
- static/client/components/Search/_Search.scss
- static/client/pages/Webpage/Webpage.tsx
- static/client/services/api/constants.ts
- static/client/services/api/index.ts
- static/client/services/api/partials/AuthApiClass.ts
- static/client/services/api/partials/BasicApiClass.ts
- static/client/services/api/partials/PagesApiClass.ts
- static/client/services/api/partials/UsersApiClass.ts
- static/client/services/api/services/auth.ts
- static/client/services/api/services/pages.ts
- static/client/services/api/services/users.ts
- static/client/services/api/services/utils.ts
- static/client/services/api/types/pages.ts
- static/client/services/api/types/users.ts
- Added two new fields to the Webpage view: Owner and Reviewers. 
- Run the project locally via `dotrun`
- Open 0.0.0.0:8104 in the browser
- Turn on VPN in order to make directory-api work
- Open any webpage's view
- Try setting an Owner field by typing someone's name into the field
- Check that only one owner can be specified
- Navigate to other pages and return to the previous page to make sure the owner is still set
- Try setting Reviewers by doing the same as with the Owner field
- Check that you can several several people
- Check that the same person cannot be selected twice
- Navigate to other pages and return to the previous page to make sure reviewers are still set
- Refresh the page and check if values of the Owner and Reviewers are still the same
- Fixes …
> [WD-13340] set owner and reviewers on each webpage

- static/client/components/OwnerAndReviewers/CustomSearchAndFilter.tsx
- In case a value is null do not show a chip in "Owner" field
- Locally this does not reproduce, since there is always a value for "Owner" field. By default there is always "Default" user. On production there is no "Default" user, so an empty object will be returned if no owner is defined. So no QA is needed, only code review.
Currently on prod:
Should be:
> do not show a chip for null in owner and reviewers

- webapp/app.py
- webapp/models.py
- Added `/get-jira-tasks/<webpage_id>` endpoint that returns an array of jira tasks, ordered by creation date
- Go to pgAdmin and add data rows to `jira_tasks` manually
- Example entry:
```
INSERT INTO jira_tasks(jira_id, webpage_id, user_id, status, created_at, updated_at)
VALUES(4, 2, 1, 2, CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP)
```
- Create a GET request to `/get-jira-tasks/<webpage_id>`
- See that an array of jira tasks is returned, ordered by `created_at`
- Example response:
```
[
{
"created_at": "2024-10-02 07:15:32.449506+00",
"id": 8,
"jira_id": "4",
"status": "2",
"user_id": 1,
"webpage_id": 2
},
{
"created_at": "2024-10-03 07:01:45.950817+00",
"id": 4,
"jira_id": "1",
"status": "2",
"user_id": 1,
"webpage_id": 2
},
{
"created_at": "2024-10-03 …
```
> Add /get-jira-tasks endpoint

- static/client/components/NewPageModal/NewPageModal.tsx
- static/client/components/NewPageModal/NewPageModal.types.ts
- static/client/components/NewPageModal/index.ts
- static/client/config/index.ts
- static/client/pages/NewWebpage/NewWebpage.tsx
- static/client/pages/Webpage/Webpage.tsx
- static/client/services/api/constants.ts
- static/client/services/api/partials/PagesApiClass.ts
- static/client/services/api/services/pages.ts
- static/client/services/api/types/pages.ts
- webapp/app.py
- webapp/helper.py
- webapp/jira.py
- Changed UI for new webpages to signify that they are new
- Added "Submit for publication" button that opens a modal with several fields. Submitting the modal form calls `/api/request-changes` endpoint that creates a Jira task for a new webpage
- Run the app locally using `dotrun`
- Open `0.0.0.0:8104` in the browser
- Check that the tree shows data for both `canonical.com` and `ubuntu.com`. If not, refresh the page and check again (the DB might be filling up, which can take a bit of a time)
- Click on `Request new page` button in the sidebar
- Make sure you have a VPN connection on
- Fill in the fields that are required for "Save and generate copy doc" button to become enabled.
- those are "URL title", "Location" and "Owner"
- Click on the "Save and generate copy doc" button and check …
> [WD-13390] Request creation of Jira task for a new webpage

- static/client/components/NewPageModal/NewPageModal.types.ts
- static/client/components/NewPageModal/index.ts
- static/client/components/OwnerAndReviewers/Owner.tsx
- static/client/components/OwnerAndReviewers/Reviewers.tsx
- static/client/components/RequestTaskModal/RequestTaskModal.tsx
- static/client/components/RequestTaskModal/RequestTaskModal.types.ts
- static/client/components/RequestTaskModal/index.ts
- static/client/pages/Webpage/Webpage.tsx
- static/client/services/api/constants.ts
- static/client/services/api/partials/PagesApiClass.ts
- static/client/services/api/services/pages.ts
- static/client/services/api/types/pages.ts
- webapp/app.py
- webapp/helper.py
- Fixed sorting of the webpages that were fetched from the database
- Added "Request changes" button to a Webpage view that will create a Jira task for copy updates and page refreshes
- Added "Request removal" button on a Webpage view that will create a Jira task for removing an existing page, or remove a webpage if it's new
- Run the app locally using `dotrun`
- Open `0.0.0.0:8104` in your browser
- Check that the tree is well sorted alphabetically (if not, clear up the database and make it propagate from the repository again)
- Open an existing page (not new one) and click on "Request changes" button. 
- This should open a modal. Fill in the required fields and click on "Submit" button
- Check that a new Jira task is created and is shown on the webpage view
- Click on the link to Jira …
> [WD-13392] Request changes and remove existing webpage functionality

- webapp/__init__.py
- webapp/app.py
- webapp/settings.py
- Added cache control headers to the `/api/get-tree` endpoint. We often need to ask IS to clear the content-cache whenever the results from this endpoint are stale, especially when no data is returned.
- Open https://websites-content-system-77.demos.haus/api/get-tree/ubuntu.com/main and check that the `Cache-Control: no-store` header is set.
> Removed get-tree from cache

- pyproject.toml
- webapp/gdrive.py
- webapp/models.py
- webapp/settings.py
- webapp/site_repository.py
- webapp/tests/fixtures.py
- webapp/tests/test_gdrive.py
- Prevented application crash when google auth fails
- Added type annotations for google drive
- Added tests and mocks for the google drive client
- Check that the demo runs 
[WD-16241](https://warthogs.atlassian.net/browse/WD-16241?atlOrigin=eyJpIjoiMWM0Mzg0MzkwOGIxNDZiMGEwN2JkZDJmNTA3OWNkODMiLCJwIjoiaiJ9)
[WD-16241]: https://warthogs.atlassian.net/browse/WD-16241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix crash when google creds are unavailable

- templates/login.html
- webapp/__init__.py
- webapp/sso.py
- Added an explicit login page to comply with login.ubuntu.com SSO configuration. 
Logging in with SSO is inconsistent on staging and production due to CORS headers being modified or stripped by the content-cache during the redirect to login.ubuntu.com. With this page, the redirect is triggered by the user hence avoiding needing CORS.
- Open the demo. If not logged in, you should be directed to `/login_page`. Clicking the log in button should trigger the sso flow, and redirect you to the dashboard.
- Logging out should redirect you to `/login_page`
> Added login page for sso compliance

- static/client/components/Search/Search.tsx
- Show domain/project name along with page, in search results.
- View the application in your browser at: https://cs-canonical-com-97.demos.haus/
- Login using U1, if not already logged in.
- Using searchbar at the top, search for web pages.
- Verify the project name is visible in search results.
- Fixes [WD-17634](https://warthogs.atlassian.net/browse/WD-17634)
- Before
- After
[WD-17633]: https://warthogs.atlassian.net/browse/WD-17633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WD-17634]: https://warthogs.atlassian.net/browse/WD-17634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix ambiguous search results

- static/client/components/OwnerAndReviewers/Owner.tsx
- static/client/components/OwnerAndReviewers/Reviewers.tsx
- Update page owner and reviewers in real-time, without having to reload the webpage to update pages tree.
- Open the [Demo](https://cs-canonical-com-103.demos.haus/) in your browser.
- Select any project from the left sidebar, and open any page from the pages tree.
- Update the owner for the web page. Select any other page from the pages tree and then come back to the previously modified page. The page should show the updated owner.
- Update the reviews for the web page. Select any other page from the pages tree and then come back to the previously modified page. The page should show the updated reviewers.
- All the modifications should remain visible without having to reload the webpage.
- Fixes #[WD-17983](https://warthogs.atlassian.net/browse/WD-17983)
[WD-17983]: …
> feat: Update reviewers and owners for a page in real-time, without having to reload (WD-17983)

- static/client/components/Breadcrumbs/Breadcrumbs.tsx
- static/client/components/MainLayout/MainLayout.test.tsx
- static/client/components/MainLayout/MainLayout.tsx
- static/client/components/Navigation/Navigation.tsx
- static/client/components/Navigation/NavigationItems/NavigationItems.tsx
- static/client/components/Search/Search.tsx
- static/client/components/SiteSelector/SiteSelector.tsx
- static/client/main.test.tsx
- static/client/pages/Main/Main.tsx
- static/client/services/routes/index.tsx
- templates/login.html
- webapp/__init__.py
- webapp/app.py
- webapp/sso.py
- Moved the app dashboard to /app. 
The content-cache has non-editable cache headers for the root path, which means our root path `/` should be cacheable. We _don't_ want the dashboard to be cachable, as it will retain invalid state briefly after logout.
In addition, if we keep the dashboard on the root path, `/`, it will be cached as the response after login, so any subsequent requests won't be authenticated. 
The dashboard code itself is served from an SPA whose url changes on each deployment, so it will be unaffected by this change, and can be cached as normal.
- Open the demo, and if not logged in you should be redirected to the root path. If you try to open a restricted link e.g. `/app` you should be redirected to `/login_page`.
- Logging in should redirect you to the path you made …
> Moved dashboard to /app endpoint

- static/client/App.scss
- static/client/components/RequestTaskModal/RequestTaskModal.tsx
- Add tooltips to request types when creating a Jira request.
- Open the [Demo](https://cs-canonical-com-101.demos.haus/) in your browser.
- Select any project from the sidebar, and open any page.
- Click on the green `Request Changes` button and a modal will be displayed.
- Verify the `information` icon next to radio buttons, and hover on each icon to see the tooltip telling more about each request type.
- Fixes #[WD-16245](https://warthogs.atlassian.net/browse/WD-16245)
[WD-16245]: https://warthogs.atlassian.net/browse/WD-16245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WD-16245 Add tooltips to request types when creating a Jira request

- webapp/helper.py
- webapp/routes/user.py
- webapp/sso.py
- Checked the existence of logged in user in "users" table, and if negative, fetched user info from canonical directory and saved in users table
- Stored user id in session
- Added an endpoint `/api/current-user` to fetch currently logged in user's info
- Added a helper function called `get_user_from_directory_by_key` which fetches a user from canonical directory by a given key,value.
Please note that you need to test it locally, because the directory API on demo is currently not working and is being fixed in a different task.
- Check out this PR and run the application using `dotrun` command locally.
- Open `localhost:8104` in your browser.
- Log in using Ubuntu SSO if not already.
- Make sure you have the VPN on. (This is required to fetch data from directory API)
- Call the …
> Backend functionality for getting current logged in user's information from canonical directory, and storing it in users table upon login

- static/client/App.tsx
- static/client/components/Navigation/Navigation.tsx
- static/client/components/Navigation/_Navigation.scss
- static/client/pages/Main/Main.tsx
- static/client/services/api/constants.ts
- static/client/services/api/hooks/auth.ts
- static/client/services/api/partials/UsersApiClass.ts
- static/client/services/api/services/users.ts
- static/client/store/types.ts
- Created a context to persist current user's info
- Display logged in user's name and email in the sidebar
- Setup query client provider
- Call `/api/current-user` on app load.
- Check out this PR 
- Open the file `webapp/routes/user.py` to see if it has a `current-user` GET endpoint. If not, paste the following sample endpoint
```
@user_blueprint.route("/current-user", methods=["GET"])
@login_required
def current_user():
return (
jsonify(
{
"id": 1,
"name": "Muhammad Ali",
"email": "muhammad.ali@canonical.com",
"team": "Web and Design",
"department": "Engineering",
"jobTitle": "Software Engineer I",
}
),
200,
)
```
- Run the application using dotrun command locally.
- Open localhost:8104 in your browser.
- Log in using Ubuntu SSO if not already.
- Verify the user name and email visible …
> [WD-18147] Persist currently logged in user's info on the frontend and show in sidebar

- static/client/components/Breadcrumbs/Breadcrumbs.tsx
- Fix invalid prefix
- Fix links not working
- Open the [demo](https://cs-canonical-com-109.demos.haus/)
- Login using SSO if not already logged in
- Select any project and page from the left sidebar
- Verify the breadcrumbs working properly
- Fixes [WD-18202](https://warthogs.atlassian.net/browse/WD-18202)
Before
After
[WD-18202]: https://warthogs.atlassian.net/browse/WD-18202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WD-18202] fix: invalid prefix in breadcrumbs and links not working

- static/client/components/Common/CustomSearchAndFilter.tsx
- static/client/components/OwnerAndReviewers/Owner.tsx
- static/client/components/OwnerAndReviewers/OwnerAndReviewers.types.ts
- static/client/components/OwnerAndReviewers/Products.tsx
- static/client/components/OwnerAndReviewers/Reviewers.tsx
- static/client/components/Products/Products.tsx
- static/client/components/Products/Products.types.ts
- static/client/components/Products/index.ts
- static/client/components/Reporter/Reporter.tsx
- static/client/components/Reporter/Reporter.types.ts
- static/client/components/Reporter/index.ts
- static/client/components/RequestTaskModal/RequestTaskModal.tsx
- static/client/pages/NewWebpage/NewWebpage.tsx
- static/client/pages/Webpage/Webpage.tsx
- static/client/services/api/constants.ts
- static/client/services/api/hooks/products.ts
- static/client/services/api/index.ts
- static/client/services/api/partials/PagesApiClass.ts
- static/client/services/api/partials/ProductsApiClass.ts
- static/client/services/api/services/pages.ts
- static/client/services/api/services/products.ts
- static/client/services/api/types/pages.ts
- static/client/services/api/types/products.ts
- static/client/services/api/types/query.ts
- webapp/routes/jira.py
- webapp/schemas.py
- Added a hook for fetching products from API.
- Render products drop down on update/create webpages.
- Pre-filled selected products for on an existing webpage.
- Save products when creating a new web page, using `create-page` POST request.
- Check out this PR
- Make sure you have a valid `JIRA_COPY_UPDATES_EPIC` and `JIRA_TOKEN`
- Run the application using `dotrun` command locally.
- Open localhost:8104 in your browser.
- Log in using Ubuntu SSO if not already.
- Select any project and page from the left sidebar.
- Verify the products are available in the products dropdown.
- Assign single/multiple products from the products dropdown to the webpage.
- Refresh the browser to verify if the products were saved successfully.
- Now, click on the `Request new page` button in the left side.
- …
> [WD-16243] Render, associate and update products with webpages

- konf/site.yaml
- webapp/sso.py
- Use the `canonical-webmonkeys` launchpad team if the `flask-debug` env variable is set, otherwise use the `canonical` group.
- Open the demo and confirm that it allows logging in. 
- Staging has been updated with this PR. Open https://cs.staging.canonical.com in incognito, to confirm that both teams allow access after logging in.
> feat: Use canonical launchpad group on prod

- docker-compose.yml
- Persist data across container restarts on dev enviroment.
- Fixes [WD-19796](https://warthogs.atlassian.net/browse/WD-19796)
[WD-19796]: https://warthogs.atlassian.net/browse/WD-19796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WD-19796] Persist postgres data across container restarts on local dev environemnt

- sites.yaml
- static/client/config/index.ts
- webapp/parse_tree.py
- Added `cn.ubuntu.com` and `jp.ubuntu.com`
- Added base template for jp.ubuntu.com
- Check out this [demo](https://cs-canonical-com-165.demos.haus/)
- Verify that the jp.ubuntu.com and cn.ubuntu.com projects are visible in the project dropdown in left sidebar
- Select both of these projects one by one and verify their children show up.
- Fixes [WD-19885](https://warthogs.atlassian.net/browse/WD-19885)
[WD-19885]: https://warthogs.atlassian.net/browse/WD-19885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WD-19885] Add more projects to content system + fix issue of missing children for jp.ubuntu.com

- .env
- package.json
- static/client/App.scss
- static/client/components/Navigation/NavigationElement/NavigationElement.tsx
- static/client/components/Navigation/NavigationElement/NavigationElement.types.ts
- static/client/components/Navigation/NavigationElement/NavigationElementBadge.tsx
- static/client/components/Navigation/NavigationElement/_NavigationElement.scss
- static/client/components/RequestTaskModal/RequestTaskModal.tsx
- yarn.lock
- Added tooltip icons for pages that are NEW or TO_DELETE.
- Added react-icons package that works well with dark/light theme backgrounds.
- Fixed bug: stale data after page removal.
- Run project locally.
- See if you could get the team-membership on sso page.
- Try removing existing pages and asking for new pages and see if the icon appears according to the [figma design](https://www.figma.com/design/uVXFi46C7ZgriDoWEnsv1U/24.10-Content-system-(CMS)?node-id=307-7371)
- After remove-request, navigation is refreshed to show the latest changes.
- Fixes [WD-16247](https://warthogs.atlassian.net/browse/WD-16247)
[WD-16247]: https://warthogs.atlassian.net/browse/WD-16247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WD-16247 Dev highlight webpages that are new or to be deleted

- README.md
- vite.config.ts
- Updated Readme
- Cleaned up vite.config.ts
- Check out this branch
- Run the project in dev mode and see that it works
```bash
docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgre
source .venv/bin/activate
set -a
source .env
source .env.local
set +a
```
In a separate terminal, run 
```bash
yarn dev
```
- Fixes [WD-21921](https://warthogs.atlassian.net/browse/WD-21921)
[WD-21921]: https://warthogs.atlassian.net/browse/WD-21921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WD-21921] chore: clean up HMR config

- static/client/pages/Main/Main.tsx
- static/client/pages/NewWebpage/NewWebpage.tsx
- static/client/services/routes/index.tsx
- Clean up routes
- Proper nesting of sub-routes
- Extract routes function
- Checkout this branch
```bash
docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgre
source .venv/bin/activate
set -a
source .env
source .env.local
set +a
```
Run in a separate terminal:
```bash
yarn dev
```
- Try selecting different pages and verify the routing works as expected
- Fixes [WD-21922](https://warthogs.atlassian.net/browse/WD-21922)
[WD-21922]: https://warthogs.atlassian.net/browse/WD-21922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WD-21922] chore: clean up nested routes

- webapp/routes/jira.py
- webapp/schemas.py
- Added a new endpoint `/api/attach-jira-with-webpage` to be called by people from content team.
- Check out this branch
- Run the project using 
```bash
dotrun build && dotrun
```
- Call the following endpoint with the payload
`POST localhost:8104/api/attach-jira-with-webpage`
```json
{
"jira_id":  "WD-1234",
"copy_doc_link": "https://docs.google.com/document/d/19TIwT-GU5wADQmohicj14MnpHEqNqp0422WLunFsbJU"
}
```
- Verify the following success response
```json
{
"message": "Jira task attached successfully"
}
```
- Additionally, you can ssh into your postgres container, and verify the presence of new record in `jira_tasks` table.
- Fixes …
> [WD-22036] feat: attach Jira task with webpage, provided copydoc link

- migrations/versions/2e86822886aa_add_ext_to_webpages.py
- static/client/components/Breadcrumbs/Breadcrumbs.tsx
- static/client/components/Navigation/NavigationElement/NavigationElement.tsx
- static/client/components/Views/TableView/TableViewRowItem.tsx
- static/client/services/api/types/pages.ts
- static/client/services/tree/pages.ts
- webapp/models.py
- webapp/parse_tree.py
- webapp/site_repository.py
**Note**: Revert this temporary QA change before merging
```python
if True or not webpages or self._has_incomplete_pages(webpages):
``` 
- Exclude partials and manually provided excluded directories from tree generation
- Store node extension e.g., .html, .md, .dir
- Disable non-webpage nodes in sidebar tree so they are not clickable
- Disable breadcrumbs for non-webpage url paths so they are not clickable
- Hide non-webpage nodes from table view
- [drive by]: modify the `findPage` helper to conditionally return bool or webpage object
- Added tooltip on disabled parts of the breadcrumb
- Clone this repo and check out this PR
- Run the project using
```bash
rm -rf .venv
docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgre
docker run -d -p 6379:6379
python -m venv .venv
source …
```
> [WD-22062] Make non-webpage nodes unclickable and exclude partials

- package.json
- static/client/pages/Webpage/Webpage.tsx
- webapp/parse_tree.py
Currently, the content system only supports and lists .html files. Some of our pages on various sites are markdown files. We need to be able to show those markdown pages as well, for content team.
- Added .md files in sites tree
- Parse .md files to extract metadata e.g., title, description and copydoc link.
- Check out this repo
```bash
dotrun
```
In a different terminal, run
```bash
dotrun exec celery -A webapp.app.celery_app worker -B  --loglevel=DEBUG
```
In another terminal, run 
```bash
yarn dev
```
- Access the application on localhost:8104/app
- Wait for the projects to load
- Select Table View > ubuntu.com
- Verify the following pages are listed, and are accessible …
> [WD-22501] feat: include and parse markdown files in project trees on content system

- static/client/components/Navigation/Navigation.tsx
- static/client/components/Navigation/NavigationElement/NavigationElement.tsx
- static/client/components/RequestTaskModal/RequestTaskModal.tsx
- static/client/components/Search/Search.services.ts
- static/client/components/Search/Search.tsx
- static/client/components/Views/TableView/ProjectTitle.tsx
- static/client/pages/Main/Main.tsx
- static/client/pages/NewWebpage/NewWebpage.tsx
- static/client/pages/Webpage/Webpage.tsx
- static/client/services/api/hooks/pages.ts
- static/client/services/api/hooks/projects.ts
- static/client/services/api/types/pages.ts
- static/client/services/api/types/query.ts
- static/client/services/routes/index.tsx
- static/client/services/tree/pages.ts
- webapp/routes/jira.py
When a user clicks on `Request New Page` button, fills out details and submits the form, the request takes a lot of time because it has to:
1. Create a google copydoc
2. Re-fetch the entire tree (all the projects) to invalidate cache
3. Refresh the page
This wait time can be reduced by:
1. Eliminating the need to re-fetch the entire tree (by optimizing the flow of data)
2. Eliminating the need to refresh
3. Invalidating cache on the backend, after creating a new webpage
- Invalidate cache for corresponding repository after creating a new webpage, within create-page request
- Add a new helper function to insert a webpage w.r.t. to it's parent, within the tree.
- Update the tree after creating a new webpage, in realtime, without having to re-fetch the tree or reload the page.
- Drive-by: …
> [WD-23309] feat: optimize page creation flow for better performance

- README.md
- static/client/components/OwnerAndReviewers/Owner.tsx
- static/client/components/RequestTaskModal/RequestTaskModal.tsx
- static/client/config/index.ts
- static/client/global.d.ts
- static/client/services/api/hooks/pages.ts
- tests/config.ts
- tests/index.spec.ts
- tests/project.spec.ts
- tests/utils/common.ts
- tests/views/table-view.spec.ts
- Updated failing playwright tests after recent layout changes
- Added new tests for table view
-  Create a new branch from this branch and raise a PR to merge your branch to this branch
- This will trigger the playwright actions on your PR
- Check out this repo
- Make sure you have the following in your env
```
DISABLE_SSO=1 
```
```bash
dotrun
```
In a different terminal, run
```bash
dotrun exec celery -A webapp.app.celery_app worker -B  --loglevel=DEBUG
```
In another terminal, run 
```bash
yarn dev
```
The application should be accessible at localhost:8104/app and should show loading when cloning repositories
- Run playwright tests in a terminal, using
```bash …
```
> [WD-22490] chore: update playwright tests

- README.md
- data/sites.yaml
- entrypoint
- static/client/config/index.ts
- static/client/services/api/constants.ts
- webapp/context.py
- webapp/github.py
- webapp/parse_tree.py
- webapp/routes/tree.py
- webapp/scheduled_tasks.py
- webapp/site_repository.py
- Removed "branch" parameter from "get-tree" endpoint, since we always use "main" branch
- Increased gunicorn's timeout to 1 minute, since default 30 seconds might not be enough to clone a repository
- Added "snapcraft.io", "charmhub.io", "netplan.io" to a list of projects to be fetched
- "canonical.design" is temporarily commented out in the list of projects, since the [repository's](https://github.com/canonical/canonical-design) name is not correct at the moment. As soon as it's fixed, we will uncomment it as well.
- Check out this repo
```bash
dotrun
```
In a different terminal, run
```bash
dotrun exec celery -A webapp.app.celery_app worker -B  --loglevel=DEBUG
```
In …
> [WD-23891] add more projects

- rockcraft.yaml
The git binary is not currently accessible in the charm.
- Added binary path from staging environment
- Check that deployments to staging and production work as expected
- Fixes [WD-XXX](https://warthogs.atlassian.net/browse/WD-XXX)
> feat: stage git binary

- static/client/App.scss
- static/client/components/Views/TableView/ProjectTitle.tsx
- static/client/components/WebpageAssets/Asset.tsx
- static/client/components/WebpageAssets/index.tsx
- static/client/config/index.ts
- static/client/pages/Webpage/Webpage.tsx
- static/client/services/api/constants.ts
- static/client/services/api/hooks/assets.ts
- static/client/services/api/partials/PagesApiClass.ts
- static/client/services/api/services/pages.ts
- static/client/services/api/types/assets.ts
- webapp/routes/webpage.py
- webapp/scheduled_tasks.py
- Added pagination to `/api/get-webpage-assets` endpoint
- Render paginated assets in a grid on a webpage
- Check out this repo
```bash
dotrun
```
In a different terminal, run
```bash
dotrun exec celery -A webapp.app.celery_app worker -B  --loglevel=DEBUG
```
In another terminal, run 
```bash
yarn dev
```
- Access the application on localhost:8104/app
- Wait for the projects to load, and assets to parse
- Open any webpage which is expected to have assets
- It should show all the assets, on that webpage
- Click around pagination to verify pagination works
- Clicking on "View" button should take you to asset's details page on assets manager
- Clicking on "Edit" button should …
> [WD-24286] feat: Render paginated assets on a web page
