canonical/cs.canonical.com

webapp/parse_tree.py
To add Canonical.com to the list of projects
- Run the app 
- Try localhost:8104/get-tree/canonical.com
- The relevant tree structure should be present
=> WD-11985 Added canonical.com to the list of projects

webapp/app.py, webapp/parse_tree.py, webapp/site_repository.py
-  Corrected the name of the paths in Tree structure
-  Corrected the issue of cloning the repos recursively
- Check if the names are correct
- Check in container if the repos are being set one at right path
=> WD-12218 Fixed Naming for Paths

webapp/site_repository.py
- Fixed `file not found error` when making multiple parallel queries by using absolute paths
- Clone this repo and run the project
- Make multiple tree requests at the same time, such as `/get-tree/ubuntu.com`, `/get-tree/canonical.com` etc
- The tree structure should be returned for each repository
- Github has a rate limit, so after a certain number of queries you might see a github error message in debug mode
[WD-12505](https://warthogs.atlassian.net/browse/WD-12505?atlOrigin=eyJpIjoiNGI4ODBkMTg4NmI5NGM3ZmE2ZDAxZjkzYzA5ZjRhZjQiLCJwIjoiaiJ9)
[WD-12505]: https://warthogs.atlassian.net/browse/WD-12505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Use absolute paths

static/client/App.scss, static/client/_settings.scss, static/client/components/Breadcrumbs/Breadcrumbs.tsx, static/client/components/Breadcrumbs/Breadcrumbs.types.ts, static/client/components/Breadcrumbs/index.ts, static/client/components/MainLayout/MainLayout.tsx, static/client/components/MainLayout/_MainLayout.scss, static/client/components/Navigation/Navigation.tsx, static/client/components/Navigation/NavigationBanner/NavigationBanner.tsx, static/client/components/Navigation/NavigationElement/NavigationElement.tsx, static/client/components/Navigation/NavigationItems/NavigationItems.tsx, static/client/components/Navigation/_Navigation.scss, static/client/components/Search/Search.services.ts, static/client/components/Search/Search.tsx, static/client/components/SiteSelector/SiteSelector.tsx, static/client/components/SiteSelector/index.ts, static/client/config/index.ts, static/client/pages/Webpage/Webpage.tsx, static/client/pages/Webpage/_Webpage.scss, static/client/store/index.ts, static/client/store/types.ts, webapp/app.py
- Redesigned according to the wireframe in Figma: https://www.figma.com/design/uVXFi46C7ZgriDoWEnsv1U/24.10-Content-system?node-id=16-2320&t=B6Cu2fHvqikmi2b0-4
- Added breadcrumbs
- Created a separate SiteSelector component to select a project
- Fixed bugs related to routing and state
- Clone the repo
- Run `dotrun --release 1.1.0-rc1 build` to build the app
- Run `dotrun --release 1.1.0-rc1 serve` to run it locally
- Open `0.0.0.0:8104` locally in your browser
- Check the UI and components and see if all works as expected
- Fixes https://warthogs.atlassian.net/browse/WD-13865
It could be helpful to provide some screenshots to aid in QAing the change.
=> [WD-13865] redesign UI

konf/site.yaml
- Update site.yaml to include directory-api token
=> Update site.yaml to include directory-api token

migrations/versions/0bd6fd83b781_.py, webapp/app.py
- Created migration to change model field `JiraTask.created_at` type from `VARCHAR` to `TIMESTAMP`
- Run the migration, and then start the site with
```bash
flask --app webapp.app db upgrade
```
=> Set updated_at to timestamp from varchar

.gitignore, requirements.txt, webapp/cache.py, webapp/site_repository.py, webapp/tests/test_site_repository.py
- Updated cloning mechanism to only clone the folder `templates`
- Added pytest and basic test case
- CI checks should be passing
- Open the [demo](https://websites-content-system-74.demos.haus/) check that the tree is populated
=> Clone only templates folder

requirements.txt, webapp/__init__.py, webapp/sso.py
- Added flask cors for `login.ubuntu.com`
- Open the demo and log in and out. There should not be any errors
- On the demo main page, check the response for `access-control-allow-origin` header
=> Added CORS library

README.md, package.json, templates/index.html, webapp/app.py
- Added HMR.
- Checkout this branch locally.
- Make sure to update the env (refer to the hot module reloading section in the readme)
- Spin up the project using `docker compose up -d` and `dotrun`.
- Open up any file from /static/client/* and make a change.
- Check that the change is visible in the browser instantly and without having to reload.
- Fixes [WD-17728](https://warthogs.atlassian.net/browse/WD-17728)
[WD-17728]: https://warthogs.atlassian.net/browse/WD-17728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Enable Hot Module Reloading for quicker change refresh and better dev experience

static/client/components/Navigation/NavigationItems/NavigationItems.tsx, static/client/components/OwnerAndReviewers/CustomSearchAndFilter.tsx, static/client/components/RequestTaskModal/RequestTaskModal.tsx
- Fixed a few console errors.
- More description about errors [here](https://warthogs.atlassian.net/browse/WD-17982)
- Fixes #[WD-17982](https://warthogs.atlassian.net/browse/WD-17982)
[WD-17982]: https://warthogs.atlassian.net/browse/WD-17982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WD-17982 Fix console errors

static/client/components/RequestTaskModal/RequestTaskModal.tsx
- Updated definitions
- Open this [demo](https://cs-canonical-com-116.demos.haus/) in your browser.
- Select any project from the sidebar, and open any page.
- Click on the green `Request Changes` button and a modal will be displayed.
- Hover on information icons to see the tooltip telling more about each request type.
- Verify the content to match that specified [here](https://warthogs.atlassian.net/browse/WD-18356)
- Fixes [WD-18356](https://warthogs.atlassian.net/browse/WD-18356)
[WD-18356]: https://warthogs.atlassian.net/browse/WD-18356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WD-18356] Update definitions for Copy update and Page refreshes

README.md
- Updated Readme
- List down steps to update an environment variable name on production pods
-  The best way would be to try out these commands for any of the staging pods.
- Fixes [WD-18341](https://warthogs.atlassian.net/browse/WD-18341)
[WD-18341]: https://warthogs.atlassian.net/browse/WD-18341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WD-18341] List steps to update env on prod pods

static/client/components/Navigation/NavigationItems/NavigationItems.tsx
- Fixed highlighted page in nav
- Open [demo](https://cs-canonical-com-124.demos.haus/) and make sure that selected pages in left sidebar are also highlighted
- Fixes [WD-18864](https://warthogs.atlassian.net/browse/WD-18864)
[WD-18864]: https://warthogs.atlassian.net/browse/WD-18864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WD-18864] Fixed selected page not highlighted in sidebar

static/client/components/RequestTaskModal/RequestTaskModal.tsx
- Fixed redirection
- Fixes #[WD-19149](https://warthogs.atlassian.net/browse/WD-19149)
[WD-19149]: https://warthogs.atlassian.net/browse/WD-19149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WD-19149] Fixed redirection on removing a NEW webpage

static/client/components/JiraTasks/JiraTasks.tsx, static/client/components/RequestTaskModal/RequestTaskModal.tsx, static/client/services/api/types/pages.ts, webapp/routes/jira.py, webapp/schemas.py
- Added a field to provide redirect_url when requesting a page removal
- Clear cache after removing a NEW webpage and update side navigation
- [Drive by] Added a table header and table body for the jira tasks table under page details
- Check out this [demo](https://cs-canonical-com-156.demos.haus/) in your web browser.
- Select any page from the left sidebar and Click "Request Removal" button.
- Verify the Redirect Url field is visible
- Submit the form and make sure the redirect_url is there in the payload (Please note the form submission will not work on the demo. If you want to test form submission, you will have to do so locally)
- Create a new webpage and make sure its visible in the side navigation
- Remove the newly created webpage and verify it's removed from the side navigation
- …
=> [WD-16291] Add redirect_url + Clear cache on NEW page removal and update side navigation

static/client/pages/NewWebpage/NewWebpage.tsx
- Design changes for the new webpage UI
- Check out this branch and run the project
```
python -m venv .venv
source .venv/bin/activate
python -m pip install -r requirements.txt
set -a
source .env
source .env.local
set +a
unset REDIS_HOST
unset REDIS_PORT
```
- Access the application on localhost:5000
- Click on "+ Request new webpage" button
- Verify the UI matches [figma design](https://www.figma.com/design/uVXFi46C7ZgriDoWEnsv1U/cs.canonical.com---Content-system--CMS-?node-id=682-38136&t=YrxX4fWmnWp8UzYR-0)
- Fixes [WD-21516](https://warthogs.atlassian.net/browse/WD-21516)
[WD-21516]: https://warthogs.atlassian.net/browse/WD-21516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …
=> [WD-21516] chore(ui): update create new webpage's page UI

webapp/helper.py
- Updated url for directory API
- Try setting owners/reviewers and see if users are being loaded up/
=> Bugfix: Updated url for directory API

static/client/components/Navigation/NavigationElement/NavigationElement.tsx, static/client/components/Views/FilterTableView/FilterandSearch.tsx, static/client/components/Views/FilterTableView/_FilterTableView.scss
- Fixed dark icon in tree view
- Drive by: Fixed "Apply" and "Cancel" filter buttons size
- Drivy by: Cleaned up some css and fixed mismatching styles for the filters box
- Checkout this branch
```bash
docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgre
source .venv/bin/activate
set -a
source .env
source .env.local
set +a
```
Run in a separate terminal:
```bash
yarn dev
```
- Submit a new page request by clicking on the "Request new page" button
- Verify the newly created page is visible in the tree view on the left
- Verify the new page icon color is in contrast with the sidebar
=> fix: dark icon

.github/workflows/deploy.yaml
- Refresh the charm if it exists, otherwise deploy it
=> feat: Refresh or deploy charm

.github/workflows/deploy.yaml
- Fixed a bug (A missing flag)
=> Fix deployment script bug
